version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: secilstore-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data:
